apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
  labels:
    app: {{ service_name }}
spec:
  selector:
    app: {{ service_name }}
  ports:
    - name: http
      port: {{ port }}
      targetPort: http
